### ISSUE TITLE
Deprecation warning for collections.Callable under Python 3.7

### ISSUE THREAD

**Issue by jonemo** [rbarrois/xworkflows#16]
While running tests for a project that uses xworkflows version 1.0.4 under Python 3.7 I recevied the following warning:

```
/Users/myusername/.virtualenvs/myrepo/lib/python3.7/site-packages/xworkflows/compat.py:26: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return isinstance(var, collections.Callable)
```

This is the line where the warning originates: https://github.com/rbarrois/xworkflows/blob/4a94b04ba83cb43f61d4b0f7db6964a667c86b5b/src/xworkflows/compat.py#L26

The deprecation warning is for using `collections.Callable` instead of `collections.abc.Callable`. The `Callable` class has moved in Python 3.3:

> New in version 3.3: Formerly, this module was part of the collections module.

Source: https://docs.python.org/3.7/library/collections.abc.html#module-collections.abc

Because xworkflows does not claim support for Python 3.0, 3.1, 3.2, and 3.3 ([see setup.py](https://github.com/rbarrois/xworkflows/blob/master/setup.py#L67-L72), it should be safe to simply update this line. Alternatively, replace the import with

```
try:
    from collections.abc import Callable
except ImportError:
    from collections import Callable
```

**Comment by rbarrois** [comment]
Sorry for the long delay, this has now been finally fixed!
